Fix Crash #7 caused by Time: 8/30/18 2:14 PM Description: Unexpected error
java.lang.ClassCastException: net.minecraft.client.audio.PositionedSoundRecord cannot be cast to net.aeronica.mods.bard_mania.client.audio.NoteSound
	at net.aeronica.mods.bard_mania.client.audio.SoundHelper.PlayStreamingSourceEvent(SoundHelper.java:122)